#pragma once

#include <stdbool.h>

#include "core.h"

#define MMIO_DEVICE_RSV 64

// DEVICE INFO

#define DMA_CNTL_DO 1

#define POWER_CNTL_SHUTDOWN 1
#define POWER_CNTL_RESTART (1 << 1)

#define CONSOLE_CNTL_INTERRUPT 1
#define CONSOLE_CNTL_IN_BLOCK (1 << 1)

// DEVICE REGISTERS

#define DMA_REG_DST_ADDR 0
#define DMA_REG_SRC_ADDR 4
#define DMA_REG_DST_INC 8
#define DMA_REG_SRC_INC 12
#define DMA_REG_LEN 16
#define DMA_REG_TRANS_SIZE 20
#define DMA_REG_CNTL 24

#define POWER_REG_CNTL 0

#define CONSOLE_REG_IN 0
#define CONSOLE_REG_OUT 4
#define CONSOLE_REG_IN_SIZE 8
#define CONSOLE_REG_RSV 12
#define CONSOLE_REG_BATCH_SIZE 16
#define CONSOLE_REG_CNTL 20

#define RIC_REG_DEVADDR 0

// DEVICE ADDRESSES

#define DMA0_BASE MMIO_BASE
#define DMA0_DST_ADDR (DMA0_BASE + DMA_REG_DST_ADDR)
#define DMA0_SRC_ADDR (DMA0_BASE + DMA_REG_SRC_ADDR)
#define DMA0_DST_INC (DMA0_BASE + DMA_REG_DST_INC)
#define DMA0_SRC_INC (DMA0_BASE + DMA_REG_SRC_INC)
#define DMA0_LEN (DMA0_BASE + DMA_REG_LEN)
#define DMA0_TRANS_SIZE (DMA0_BASE + DMA_REG_TRANS_SIZE)
#define DMA0_CNTL (DMA0_BASE + DMA_REG_CNTL)
#define DMA0_END (DMA0_CNTL + 4)

#define DMA1_BASE (MMIO_BASE + MMIO_DEVICE_RSV)
#define DMA1_DST_ADDR (DMA1_BASE + DMA_REG_DST_ADDR)
#define DMA1_SRC_ADDR (DMA1_BASE + DMA_REG_SRC_ADDR)
#define DMA1_DST_INC (DMA1_BASE + DMA_REG_DST_INC)
#define DMA1_SRC_INC (DMA1_BASE + DMA_REG_SRC_INC)
#define DMA1_LEN (DMA1_BASE + DMA_REG_LEN)
#define DMA1_TRANS_SIZE (DMA1_BASE + DMA_REG_TRANS_SIZE)
#define DMA1_CNTL (DMA1_BASE + DMA_REG_CNTL)
#define DMA1_END (DMA1_CNTL + 4)

#define DMA2_BASE (MMIO_BASE + MMIO_DEVICE_RSV * 2)
#define DMA2_DST_ADDR (DMA2_BASE + DMA_REG_DST_ADDR)
#define DMA2_SRC_ADDR (DMA2_BASE + DMA_REG_SRC_ADDR)
#define DMA2_DST_INC (DMA2_BASE + DMA_REG_DST_INC)
#define DMA2_SRC_INC (DMA2_BASE + DMA_REG_SRC_INC)
#define DMA2_LEN (DMA2_BASE + DMA_REG_LEN)
#define DMA2_TRANS_SIZE (DMA2_BASE + DMA_REG_TRANS_SIZE)
#define DMA2_CNTL (DMA2_BASE + DMA_REG_CNTL)
#define DMA2_END (DMA2_CNTL + 4)

#define DMA3_BASE (MMIO_BASE + MMIO_DEVICE_RSV * 3)
#define DMA3_DST_ADDR (DMA3_BASE + DMA_REG_DST_ADDR)
#define DMA3_SRC_ADDR (DMA3_BASE + DMA_REG_SRC_ADDR)
#define DMA3_DST_INC (DMA3_BASE + DMA_REG_DST_INC)
#define DMA3_SRC_INC (DMA3_BASE + DMA_REG_SRC_INC)
#define DMA3_LEN (DMA3_BASE + DMA_REG_LEN)
#define DMA3_TRANS_SIZE (DMA3_BASE + DMA_REG_TRANS_SIZE)
#define DMA3_CNTL (DMA3_BASE + DMA_REG_CNTL)
#define DMA3_END (DMA3_CNTL + 4)

#define POWER0_BASE (MMIO_BASE + MMIO_DEVICE_RSV * 4)
#define POWER0_CNTL (POWER0_BASE + POWER_REG_CNTL)
#define POWER0_END (POWER0_CNTL + 4)

#define CONSOLE0_BASE (MMIO_BASE + MMIO_DEVICE_RSV * 5)
#define CONSOLE0_IN (CONSOLE0_BASE + CONSOLE_REG_IN)
#define CONSOLE0_OUT (CONSOLE0_BASE + CONSOLE_REG_OUT)
#define CONSOLE0_IN_SIZE (CONSOLE0_BASE + CONSOLE_REG_IN_SIZE)
#define CONSOLE0_BATCH_SIZE (CONSOLE0_BASE + CONSOLE_REG_BATCH_SIZE)
#define CONSOLE0_CNTL (CONSOLE0_BASE + CONSOLE_REG_CNTL)
#define CONSOLE0_END (CONSOLE0_CNTL + 4)

#define RIC0_BASE (MMIO_BASE + MMIO_DEVICE_RSV * 6)
#define RIC0_DEVADDR (RIC0_BASE + RIC_REG_DEVADDR)
#define RIC0_END (RIC0_DEVADDR + 4)

bool mmio_read(AresState *g, u32 mmio_addr, int size, u32 *ret);
bool mmio_write(AresState *g, u32 mmio_addr, int size, u32 value);
